language: go

go:
- "1.13"

before_script:
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - $GOPATH/bin/golangci-lint run ./pkg/tracker/...
  - $GOPATH/bin/golangci-lint run ./pkg/collector/...
  - $GOPATH/bin/golangci-lint run main.go

notifications:
  email: false
