apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-netc
  namespace: kube-system
  labels:
    k8s-app: kube-netc
spec:
  selector:
    matchLabels:
      name: kube-netc
  template:
    metadata:
      labels:
        name: kube-netc
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kube-netc
        image:  kube-netc:lastest
        imagePullPolicy:  Never
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers